// Auth
const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
const AUTHENTICATION_SIGNOUT = 'AUTHENTICATION_SIGNOUT';

// Blog
const BLOG_FAILURE = 'BLOG_FAILURE';
const BLOG_ADD = 'BLOG_ADD';
const BLOG_RECIEVE_SINGULAR = 'BLOG_RECIEVE_SINGULAR';
const BLOG_RECIEVE_MULTIPLE = 'BLOG_RECIEVE_MULTIPLE';

// User
const USER_FAILURE = 'USER_FAILURE';
const USER_RECIEVE_SINGLUAR = 'USER_RECIEVE_SINGLUAR';

// Stat
const STAT_FAILURE = 'STAT_FAILURE';
const STAT_RECIEVE_MULTIPLE = 'STAT_RECIEVE_MULTIPLE';

// Queue
const QUEUE_FAILURE = 'QUEUE_FAILURE';
const QUEUE_RECIEVE_MULTIPLE = 'QUEUE_RECIEVE_MULTIPLE';

export {
    AUTHENTICATION_FAILURE,
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_SIGNOUT,
    BLOG_FAILURE,
    BLOG_ADD,
    BLOG_RECIEVE_SINGULAR,
    BLOG_RECIEVE_MULTIPLE,
    USER_FAILURE,
    USER_RECIEVE_SINGLUAR,
    STAT_FAILURE,
    STAT_RECIEVE_MULTIPLE,
    QUEUE_FAILURE,
    QUEUE_RECIEVE_MULTIPLE
};
